apiVersion: v1

kind: Service

metadata:
  name: petsclinic-service

spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8090
      targetPort: 8080  
  selector:
    app: myapp
