apiVersion: v1
kind: Pod
metadata:
  name: petsclinic-app-pod
  labels:
    app: petclinic
    tier: front-end
spec:
  containers:
    - name: petscliniclatest
      image: harish1206/petsclinic:latest
      ports:
        - containerPort: 80
