apiVersion: apps/v1
kind: Deployment
metadata:
  name: petsclinic-deployment
  labels:
    app: petclinic
    tier: front-end
spec:
  replicas: 1
  template:
    metadata:
      name: petclinic-pod
      labels:
        app: petclinic
    spec:
      containers:
        - name: petscliniclatest
          image: harish1206/petsclinic:latest
  selector:
    matchLabels:
      app: petclinic
